### ISSUE TITLE
cellWidth does not alter the width of the days in the header.

### ISSUE THREAD

**Issue by zdam** [thegrubbsian/jquery.ganttView#10]
Repro: 
In example\index.html, add cellWidth:42 to the $("#ganttChart").ganttView( initialisation
- this doubles the cellWidth from the default 21

Issue:
After making this change, the gantt time series are correctly made wider, but the day numbers across the header of the gantt chart are not made wider, resulting in the periods looking like they are now double the length of time.

**Comment by lutze** [comment]
The header widths for the month and day rows are set in the CSS rather than in-line as they're consistent. These are, respectively, 'div.ganttview-hzheader-month' and 'div.ganttview-hzheader-day'. 

If you'd like to resize the chart generally, updates to those two declarations would resize the date header information. 

If you're looking to support resizing these programmatically, it would perhaps require selecting all elements with those two classes and specifying new temporary style properties.
